name: pyweed
channels:
- defaults
- conda-forge
- obspy
dependencies:
- python=3.5*
- basemap
- future
- matplotlib
- numpy
- obspy=1.0.3
- pandas
- pillow
- pyqt=4.11.4
- qtconsole
- pyzmq
- pip:
  - pyweed==0.4.dev2
  - geographiclib
