name: pyweed-3
channels:
- obspy
dependencies:
- python=3.5*
- basemap=1.0.7
- future=0.16.0
- matplotlib=1.5.1
- numpy=1.10.4
- obspy=1.0.2
- pandas=0.18.1
- pillow=3.4.2
- pyqt=4.11.4
- qtconsole=4.2.1
- pip:
  - geographiclib==1.47
